<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * selectionne une commande validée et son utilisateur associé
     *
     * @param [type] $utilisateur
     * @return void
     */
    public function byFacture($utilisateur)
    {
        $qb = $this->createQueryBuilder('c')
                ->where('c.utilisateur = :utilisateur')
                ->andWhere('c.valider = 1')
                ->andWhere('c.reference != 0')
                ->orderBy('c.id')
                ->setParameter('utilisateur', $utilisateur);
        
        return $qb->getQuery()->getResult();
    }
}
