<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($categorie)
    {
        // recupère les produits en fonction des categories
        $qb = $this->createQueryBuilder('p')
                    ->where('p.categorie = :categorie')
                    ->andWhere('p.disponible = 1')
                    ->orderBy('p.id')
                    ->setParameter('categorie', $categorie);

        return $qb->getQuery()
                  ->getResult();
    }

    public function recherche($chaine)
    {
        //Selectionne les produits correspondant à $chaine qui est la valeur tapée dans la barre de recherche
        $qb = $this->createQueryBuilder('p')
                    ->where('p.nom like :chaine')
                    ->andWhere('p.disponible = 1')
                    ->orderBy('p.id')
                    ->setParameter('chaine', $chaine);

        return $qb->getQuery()
                  ->getResult();
    }

    public function findArray($array)
    {
        // Function qui récupère uniquement les produits passés en $session
        $qb = $this->createQueryBuilder('p')
                    // on filtre les id qui correspondent au tableau contenant nos id defini ds le controleur
                   ->where('p.id IN (:array)')
                   ->setParameter('array', $array);
        
        return $qb->getQuery()
                  ->getResult();
    }
}
